---
title: "Global Inventory of Adaptation Monitoring Systems for CAS"
output:
  html_document:
    theme: united
    highlight: tango
    css: styles.css
keep_md: true
---

#### [View chart](https://shoummashams.github.io/full.html) {#link}

#### [Colour-blind friendly version of the chart](https://shoummashams.github.io/cb.html) {#link}

## Libraries
```{r setup, warning=FALSE, message = FALSE}
# install.packages("highcharter") # for Sankey chart
# install.packages("htmlwidgets") # for exporting Sankey chart into HTML form
# install.packages("webshot",dependencies = TRUE) # for exporting Sankey chart into image form

library(highcharter)
library(dplyr)
library(htmlwidgets)
library(webshot)
```

## Import inventory
```{r}
inventory <- read.csv("Inventory.csv")
names(inventory) <- inventory[1, ] 
df <- inventory[c(2:nrow(inventory)), ] # Remove top row
df <- subset(df, select = c("Present", "Implementation", "Type")) # Remove unnecessary columns
```

Data cleanup for Sankey usage
```{r}
data <- data.frame(append(df, c(Countries = "Countries"), after = 0)) # Make first column "Countries" to group all together initial starting point on chart

# Change Yes in Present to "Present" for visualisation

data <- subset(data, Present == "Yes")
data$Present[data$Present == "Yes"] <- "Present"

# Hide data for countries that have no data in Present to prevent empty categories
for (n in 1:nrow(data)) {
  if (data[n,"Present"] == "No data")
    data[n,"Implementation"] = NA
}

# Clean up all the Types
data$Type[data$Type == "1,3"] <- "Type 1 & 3"
data$Type[data$Type == ""] <- NA
data$Type[data$Type == "No data"] <- "Unknown Type"
data$Type[data$Type == 1] <- "Type 1"
data$Type[data$Type == 2] <- "Type 2"
data$Type[data$Type == 3] <- "Type 3"

# If Implementation is "No data" but there is a Type present, convert Type to "No data" since otherwise it creates a loop
#for (n in 1:nrow(data)) {
 # if (data[n,"Implementation"] == "No data" && data[n,"Type"] != "No data")
 #   data[n,"Type"] = "Unknown Type"
#}

# Change No data in Implementation to prevent looping in chart
data$Implementation[data$Implementation == "No data" | data$Implementation == ""] <- "Unknown"

head(data)
tail(data)
```

Labels
```{r}
# Add percentages to all labels
data1 <- data %>%
      group_by(Present) %>%
      tally()%>%
      mutate(perc = n/sum(n))%>%
      mutate(PresentNew = paste0(Present, ' (',n,' Countries)'))%>%
      select(-n, - perc)

data_w_stats <- merge(data, data1, by = "Present")

data2 <- data %>%
      group_by(Implementation) %>%
      tally()%>%
      mutate(perc = n/sum(n))%>%
      mutate(ImplNew = paste0(Implementation, ' (',round(perc* 100,1) , '%)'))%>%
      select(-n, - perc)

data_w_stats <- merge(data_w_stats, data2, by = "Implementation")

data3 <- data %>%
      group_by(Type) %>%
      tally()%>%
      mutate(perc = n/(sum(n)-2))%>% # -2 for the two countries with no implementation info
      mutate(TypeNew = paste0(Type, ' (',round(perc* 100,1), '%)'))%>%
      select(-n, - perc)

data_w_stats <- merge(data_w_stats, data3, by = "Type")

# Create final table for Sankey chart (option 1 is without countries)
dataSankey <- data_w_stats %>%
  select(PresentNew, ImplNew, TypeNew)

#dataSankey <- data_w_stats %>%
#  select(Countries, PresentNew, ImplNew, TypeNew) %>%
#  mutate(Countries = paste0(Countries, ' (',nrow(data),')'))

# Hide unnecessary information
dataSankey$TypeNew[dataSankey$TypeNew == "NA (78.6%)"] = NA
dataSankey$ImplNew[dataSankey$ImplNew == "NA (78.6%)"] = NA
```

## Create Sankey chart
```{r}
plot <- hchart(data_to_sankey(dataSankey), "sankey", name = "Global Inventory") 

## Customisation

sankey_plot <- plot %>%
  hc_title(text= "Global Inventory of National Adaptation Monitoring Systems") %>%
  hc_subtitle(text= "Sankey Diagram")  %>%
  hc_caption(text = "<b>This plot is for visualisation purposes only. Data is gathered from the inventory.<b>")%>%
  hc_add_theme(hc_theme_elementary()) %>%
  hc_plotOptions(series = list(enabled = TRUE,
                               dataLabels = list(style = list(fontSize = "15px",
                                                              color = "black",
                                                              connectorAllowed = TRUE)))) %>%
  hc_yAxis(labels = list(distance = 100)) %>%
  hc_exporting(enabled = TRUE,
               filename = "sankey")

sankey_plot
```

## Colour-blind friendly version
```{r}
cb_plot <- highchart() %>%
  hc_add_series(data = data_to_sankey(dataSankey), "sankey", name = "Global Inventory",
                hcaes(from = from, to = to, weight = weight),
                nodes = list(list(id = "Present (41 Countries)", color = "#56B4E9"), #sky blue
                             list(id = "Implemented (58.5%)", color = "#D55E00"), #orange
                             list(id = "Planned (36.6%)", color = "#CC79A7"), #pink
                             list(id = "Unknown (4.9%)", color = "black"),
                             list(id = "Type 1 & 3 (5.1%)", color = "#009E73"), #turquoise
                             list(id = "Type 1 (12.8%)", color = "#0072B2"), #blue
                             list(id = "Type 2 (12.8%)", color = "#F0E442"), #yellow-green
                             list(id = "Type 3 (61.5%)", color = "#56B4E9"),
                             list(id = "Unknown Type (12.8%)", color = "#E69F00") #pale orange
                             )) %>%
  hc_title(text= "Global Inventory of National Adaptation Monitoring Systems") %>%
  hc_subtitle(text= "Sankey Diagram")  %>%
  hc_caption(text = "<b>This plot is for visualisation purposes only. Data is gathered from the inventory.<b>")%>%
  hc_add_theme(hc_theme_elementary()) %>%
  hc_plotOptions(series = list(enabled = TRUE,
                               dataLabels = list(style = list(fontSize = "15px",
                                                              color = "black",
                                                              connectorAllowed = TRUE)))) %>%
  hc_yAxis(labels = list(distance = 100)) %>%
  hc_exporting(enabled = TRUE,
               filename = "sankey")

cb_plot
```

## Export
```{r}
htmlwidgets::saveWidget(widget = cb_plot, file = "Sankey_cb.html")
```